# plugins_builder.zsh — dynamic Antidote plugin builder

_build_plugins() {
  local dest="$HOME/.zsh_plugins.txt"
  local tmp
  tmp="$(mktemp)"

  # Always loaded; syntax highlighting is forced last (see bottom of function)
  local HIGHLIGHT_LAST="zsh-users/zsh-syntax-highlighting"
  local -a ALWAYS_ON=(
    ajeetdsouza/zoxide
    zsh-users/zsh-autosuggestions
    zsh-users/zsh-completions
    'ohmyzsh/ohmyzsh path:plugins/git'
  )

  # Binary-gated plugins: [binary]=full Antidote spec
  typeset -A IF_INSTALLED=(
    [aws]='ohmyzsh/ohmyzsh path:plugins/aws'
    [terminal-notifier]='t413/zsh-background-notify'
  )

  print -r -- "# Auto-generated by plugins_builder.zsh on $(date)" > "$tmp"

  # Always-on first
  local p
  for p in "${ALWAYS_ON[@]}"; do
    print -r -- "$p" >> "$tmp"
  done

  # Then conditionals when their commands exist
  local cmd spec
  for cmd spec in "${(@kv)IF_INSTALLED}"; do
    (( $+commands[$cmd] )) && print -r -- "$spec" >> "$tmp"
  done

  # Terminal-gated plugins
  [[ "$TERM_PROGRAM" == "iTerm.app" ]] && \
    print -r -- "ohmyzsh/ohmyzsh path:plugins/iterm2" >> "$tmp"

  # Ensure syntax highlighting is sourced last
  print -r -- "$HIGHLIGHT_LAST" >> "$tmp"

  # Write only if changed — avoids triggering an Antidote rebundle on every shell start
  if [[ ! -e "$dest" ]] || ! cmp -s "$tmp" "$dest"; then
    mv "$tmp" "$dest"
  else
    rm -f "$tmp"
  fi
}

_build_plugins
