abbr -a -- gst 'git status'
abbr -a -- glg 'git log --stat'
abbr -a -- ga 'git add'
abbr -a -- gau 'git add --update'
abbr -a -- gb 'git branch'
abbr -a -- gcmsg 'git commit -m'
abbr -a -- gc! 'git commit --amend --verbose'
abbr -a -- gco 'git checkout'
abbr -a -- gd 'git diff'
abbr -a -- gc 'git commit'
abbr -a -- gp 'git push'
abbr -a -- gds 'git diff --staged'
abbr -a -- gitignored 'git ls-files --others -i --exclude-standard'
abbr -a -- gsw 'git switch'
abbr -a -- gswc 'git switch --create'
